### ISSUE TITLE
Qual sua stack atual para novos projetos?

### ISSUE THREAD

**Issue by gmtborges** [robertoachar/ama#3]
Gostaria de saber quais ferramentas e tecnologias utiliza para um projeto do zero, banco de dados, linguagem, infraestrutura, serviço de logs e monitoramento.

Parabéns pelas contribuições que tem feito!

**Comment by robertoachar** [comment]
Gustavo, atualmente trabalho basicamente com duas stacks:

1. .Net Core para projetos corporativos
2. JavaScript para projetos profissionais/pessoais

## .Net Core

* **Banco de Dados**: Sql Server
* **Backend**: .Net Core 2.0 (Web API)
* **Front-end**: Angular
* **Staging / Production**: On-premises / Azure

## JavaScript

* **Banco de Dados**: MongoDB
* **Backend**: Node + Express (Web API)
* **Front-end**: Pug (antigo Jade) / Angular
* **Staging / Production**: now.sh / AWS

---

## Microservices

Para a arquitetura de microservices utilizo a stack de JavaScript com mais alguns recursos.

* **Banco de Dados**: mlab (MongoDB)
* **Gateway**: Node + Express + Passport (Oauth2)
* **Rest API**: Node + Express
* **Message Queue**: RabbitMQ
* **Service Workers**: Node / Python
* **Front-end**: Angular + Nginx
* **Container**: Docker
* **Orquestrador**: Kubernetes
* **Cloud**: GCP - Google Cloud Platform
* **Logs / Monitor**: StackDriver (GCP)

---

## CDN / DNS

* Quase 100% dos meus projetos estão na Cloudflare
* Utilizo o armazenamento de dados da BackBlaze (concorrente do S3 da AWS)
* Crio regras na Cloudflare para servir os dados da BackBlaze como CDN

---

## Serviços de email

* GSuite (Google)
* Dev: mailtrap
* Prod: postmark (transacional)

---

## Editor e Terminal

* Meu editor favorito é o [VS Code](https://code.visualstudio.com/). Desenvolvo quase todos os meus projetos nele.
 
* Para trabalhar com C# e .Net Core ainda prefiro o [Visual Studio](https://www.visualstudio.com).

* Tanto no PC quanto no MAC utilizo o [Hyper](https://hyper.is/) como terminal.

* Meu ambiente shell é o ZSH + [OH MY ZSH](http://ohmyz.sh/). Utilizo bastante os plugins `git`, `node`, `npm` e `z`.

* Utilizo basicamente 03 fontes: `Operator Mono`, `Inconsolata` e `Fira Code`.

---

## Ferramentas de produtividade

* Postman
* Alfred
* Trello
* Draw.io
